# Generated by Django 3.0.8 on 2020-11-06 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_center_email'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='training',
            unique_together={('name', 'center', 'dates')},
        ),
    ]
