# Generated by Django 3.0.8 on 2020-11-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_auto_20201106_0001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="name",
            field=models.CharField(max_length=250),
        ),
    ]
