# Generated by Django 3.0.8 on 2020-10-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
